version: '3.8'

services:  
  backend:
    context: ./backend
    dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8042"
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: