FROM maven:3.9.8-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:go-offline
COPY src ./src
EXPOSE 8042
ENV SPRING_PROFILES_ACTIVE=dev
CMD ["mvn", "spring-boot:run"]
