name: Build and Push Docker Compose Image to GHCR

on:
  push:
    branches:
      - cd_test
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Compose Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Compose Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Post Build Cleanup
        run: docker system prune -f --volumes
