name: Remote Deployment
on:
  push:
    branches: [ "cd_test" ] #only on cd test while testing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: masterjanic/docker-compose-ssh-deployment@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: 10.212.25.61
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          use_stack: 'true'