name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and start containers
        run: docker compose -f compose.yaml up --build
      - name: Wait for backend to be ready
        run: sleep 15
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "32735868-e71c03af-2701-4b97-a224-ce4a4b4ae536" -e "32735868-08d01012-4ff9-4564-b945-8e2e0bd896f1"
          postman collection run "32735868-bb594c6b-2cf6-4077-87b7-8c128906c69a"
          postman collection run "32735868-cbc9dc6f-b088-42ca-beb8-1ba9e32e8c26"
          postman collection run "32735868-681a915e-34c2-4f4a-99c7-7b0f9da1dc97"
          postman collection run "32735868-ab5a5e8d-5afd-4bc1-b205-1aaa6beda28c"
          postman collection run "32735868-cf1c51d7-5845-4f1a-8bd4-37085add429b"
          postman collection run "32735868-4eed7431-d778-42cd-92cb-415662490319"
          postman collection run "32735868-7d6fc73f-4354-41dc-95e1-d7891692aeda"